Repository YAPP-18th/Study_Algorithm_Team_2, pull requests merged in 2021-07, with the labels that each got.

#121 황종훈 : Programmers 17677 뉴스클러스터링
  HwangJongHoon/Programmers/Week15/뉴스클러스터링.java
Labels: Implementation, Math

#123 황종훈 : Programmers 72415 카드짝맞추기
  HwangJongHoon/Programmers/Week15/카드짝맞추기.java
Labels: Bfs, Brute Force, Permutation

#124 조수연 : Programmers 1829 카카오프렌즈 컬러링북
  SooyeonJo/Programmers/Week16/1829_카카오프렌즈컬러링북.java
Labels: Bfs

#125 황종훈 : Programmers 1829 카카오프렌즈컬러링북
  HwangJongHoon/Programmers/Week16/카카오프렌즈컬러링북.java
Labels: Dfs

#127 임준규 : Programmers 1829 카카오 프렌즈 컬러링북
  Junkyu_Lim/Week16/1829.java
Labels: Dfs
