Repository YAPP-18th/Study_Algorithm_Team_2, pull requests merged in 2021-03, with the labels that each got.

#12 임준규 : BOJ 9020 골드바흐의 추측
  Junkyu_Lim/.DS_Store
  Junkyu_Lim/Week1/.DS_Store
  Junkyu_Lim/Week1/1002_터렛.java
  Junkyu_Lim/Week1/9020_goldbach.java
  Junkyu_Lim/Week1/9461_파도반수열.java
Labels: Math

#2 임준규 : BOJ 9461 파도반수열
  Junkyu_Lim/Week1/9461_파도반수열.java
Labels: Math

#10 임인호 : BOJ 1002 터렛
  Inho/BOJ/Week1/Boj1002_터렛.java
  Inho/BOJ/Week1/Boj9020_골드바흐의추측.java
  Inho/BOJ/Week1/Boj9461_파도반수열.java
Labels: Math

#7 임인호 : BOJ 9461 파도반 수열
  Inho/BOJ/Week1/Boj9461_파도반수열.java
Labels: DP, Math

#9 조수연 : LeetCode 9 Palindrome Number
  SooyeonJo/LeetCode/Week1/1512_NumberofGoodPairs.java
  SooyeonJo/LeetCode/Week1/67_AddBinary.java
  SooyeonJo/LeetCode/Week1/9_PalindromeNumber.java
Labels: Math

#5 조수연 : LeetCode 1512 Number of Good Pairs
  SooyeonJo/LeetCode/Week1/1512_NumberofGoodPairs.java
Labels: Math

#4 황종훈 : BOJ 9461 파도반 수열
  HwangJongHoon/BOJ/Week1/Exam1002_터렛.java
  HwangJongHoon/BOJ/Week1/Exam9020_골드바흐의추측.java
  HwangJongHoon/BOJ/Week1/Exam9461_파도반수열.java
  README.md
Labels: DP, Math

#21 임인호 : BOJ 11047 동전0, BOJ 1541 잃어버린 괄호
  Inho/BOJ/Week1/boj11047_동전0.java
  Inho/BOJ/Week1/boj1541_잃어버린괄호.java
Labels: Greedy

#20 임준규 : BOJ 1541 잃어버린 괄호
  Junkyu_Lim/Week2/1541_잃어버린 괄호.java
Labels: Greedy

#19 임준규 : BOJ 11047 동전 0
  Junkyu_Lim/Week2/coin.java
Labels: Greedy

#13 조수연 : BOJ 11047 동전 0
  SooyeonJo/BOJ/Week2/11047_동전0.java
Labels: Greedy

#14 황종훈 : BOJ 1197 최소 스패닝 트리
  HwangJongHoon/BOJ/Week2/Exam1197_최소스패닝트리.java
Labels: Graph, Greedy

#15 황종훈 : BOJ 1541 잃어버린 괄호 2
  HwangJongHoon/BOJ/Week2/Exam1541_잃어버린괄호2.java
Labels: Greedy, String

#16 황종훈 : BOJ 11047 동전 0
  HwangJongHoon/BOJ/Week2/Exam11047_동전0.java
Labels: Greedy

#23 임인호 : BOJ1260 Dfs와 Bfs
  Inho/BOJ/Week2/boj11047_동전0.java
  Inho/BOJ/Week2/boj1541_잃어버린괄호.java
  Inho/BOJ/Week3/Boj1260_dfs와bfs.java
Labels: Bfs, Dfs

#25 조수연 : BOJ 1260 DFS와 BFS
  SooyeonJo/BOJ/Week3/1260_DFS와BFS.java
Labels: Bfs, Dfs

#27 황종훈 : BOJ 1260 DFS와 BFS
  HwangJongHoon/BOJ/Week3/Exam1260_DFS와BFS.java
Labels: Bfs, Dfs

#28 황종훈 : BOJ 7576 토마토
  HwangJongHoon/BOJ/Week3/Exam7576_토마토.java
Labels: Bfs

#29 황종훈 : Programmers Level3 경주로 건설
  HwangJongHoon/Programmers/Week3/경주로건설.java
Labels: Bfs
