Repository YAPP-18th/Study_Algorithm_Team_2, pull requests merged in 2021-04, with the labels that each got.

#37 임인호 : BOJ 1300 k번째 수
  Inho/BOJ/Week4/Boj10816_숫자카드2.java
  Inho/BOJ/Week4/Boj1300_k번째수.java
Labels: Binary Search

#43 조수연 : BOJ 10816 숫자 카드 2
  SooyeonJo/BOJ/Week4/10816_숫자카드2.java
  SooyeonJo/BOJ/Week4/1300_K번째수.java
  SooyeonJo/BOJ/Week4/2805_나무자르기.java
Labels: Binary Search

#38 조수연 : BOJ 2805 나무 자르기
  SooyeonJo/BOJ/Week4/2805_나무자르기.java
Labels: Binary Search

#42 황종훈 : BOJ 10816 숫자 카드 2
  HwangJongHoon/BOJ/Week4/Exam10816_숫자카드2.java
Labels: Binary Search

#41 황종훈 : BOJ 2805 나무 자르기
  HwangJongHoon/BOJ/Week4/Exam2805_나무자르기.java
Labels: Binary Search

#40 황종훈 : BOJ 1300 K번째 수
  HwangJongHoon/BOJ/Week4/Exam1300_K번째수.java
Labels: Binary Search

#54 임준규 : BOJ 14888 연산자 끼워넣기
  Junkyu_Lim/Week5/14888.java
Labels: Brute Force

#52 황종훈 : BOJ 14888 연산자 끼워넣기
  HwangJongHoon/BOJ/Week5/Exam14888_연산자끼워넣기.java
Labels: Brute Force

#53 임준규 : BOJ 1436 영화감독 숀
  Junkyu_Lim/Week5/1436.java
Labels: Brute Force

#51 조수연 : BOJ 14888 연산자 끼워넣기
  SooyeonJo/BOJ/Week5/1436_영화감독숌.java
  SooyeonJo/BOJ/Week5/14888_연산자끼워넣기.java
  SooyeonJo/BOJ/Week5/14889_스타트와링크.java
Labels: Back Tracking

#45 조수연 : BOJ 1436 영화감독 숌
  SooyeonJo/BOJ/Week5/1436_영화감독숌.java
Labels: Brute Force

#50 황종훈 : BOJ 14889 스타트와 링크
  HwangJongHoon/BOJ/Week5/Exam14889_스타트와링크.java
Labels: Brute Force

#48 황종훈 : BOJ 1436 영화감독 숌
  HwangJongHoon/BOJ/Week5/Exam1436_영화감독숌.java
Labels: Brute Force

#47 임인호 : BOJ 14888 연산자 끼워넣기
  Inho/BOJ/Week5/Boj14888_연산자끼워넣기.java
Labels: Back Tracking

#46 임인호 : BOJ 14889 스타트와 링크
  Inho/BOJ/Week5/Boj14889_스타트와링크.java
Labels: Back Tracking

#44 임인호 : BOJ 1436 영화감독 숀
  Inho/BOJ/Week5/Boj1436_영화감독숌.java
Labels: Brute Force

#66 임인호 : Programmers 위장
  Inho/Programmers/Week6/Programmers2_위장.java
Labels: Hash

#65 조수연 : Programmers 42584 주식가격
  SooyeonJo/Programmers/Week6/42578_위장.java
  SooyeonJo/Programmers/Week6/42584_주식가격.java
  SooyeonJo/Programmers/Week6/42586_기능개발.java
Labels: Stack

#55 조수연 : Programmers 42578 위장
  SooyeonJo/Programmers/Week6/42578_위장.java
Labels: Hash

#63 임인호 : Programmers 기능개발
  Inho/Programmers/Week6/Programmers2_기능개발.java
Labels: Queue

#62 임준규 : Programmers 42578 위장
  Junkyu_Lim/Week6/42578.java
Labels: Hash

#61 임준규 : Programmers 42584 주식가격
  Junkyu_Lim/Week6/42584.java
Labels: Stack

#60 임준규 : Programmers 42586 기능개발
  Junkyu_Lim/Week6/42586.java
Labels: Stack

#59 황종훈 : Programmers 위장
  HwangJongHoon/Programmers/Week6/위장.java
Labels: Hash

#58 황종훈 : Programmers 주식가격
  HwangJongHoon/Programmers/Week6/주식가격.java
Labels: Stack

#57 황종훈 : Programmers 기능개발
  HwangJongHoon/Programmers/Week6/기능개발.java
Labels: Queue

#67 조수연 : Programmers 42579 베스트앨범
  SooyeonJo/Programmers/Week7/42579_베스트앨범.java
Labels: Hash

#68 임인호 : programmers 베스트앨범
  Inho/Programmers/Week7/Programmers3_베스트앨범.java
Labels: Hash

#70 황종훈 : Programmers 42626 더 맵게
  HwangJongHoon/Programmers/Week7/더맵게.java
Labels: Heap

#71 황종훈 : Programmers 42577 전화번호 목록
  HwangJongHoon/Programmers/Week7/전화번호목록.java
Labels: Hash

#72 황종훈 : Programmers 42579 베스트앨범
  HwangJongHoon/Programmers/Week7/베스트앨범.java
Labels: Hash

#74 임준규 : Programmers 42626 스코빌 지수
  Junkyu_Lim/Week7/42626.java
Labels: Queue

#75 임준규 : Programmers 42577 전화번호부
  Junkyu_Lim/Week7/42577.java
Labels: Hash

#76 임준규 : Programmers 42579 베스트앨범
  Junkyu_Lim/Week7/42579.java
Labels: Hash

#78 임인호 : Programmers 더 맵게
  Inho/Programmers/Week7/Programmers2_더맵게.java
Labels: Heap
