Repository YAPP-18th/Study_Algorithm_Team_2, pull requests merged in 2021-05, with the labels that each got.

#79 조수연 : Programmers 42839 소수 찾기
  SooyeonJo/Programmers/Week8/42839_소수찾기.java
Labels: Back Tracking

#80 임인호 : Programmers 문자열 압축
  Inho/Programmers/Week8/Programmers2_문자열압축.java
Labels: Brute Force

#83 황종훈 : Programmers 60057 문자열 압축
  HwangJongHoon/Programmers/Week8/문자열압축.java
Labels: Queue, String

#86 임인호 : Programmers 소수찾기
  Inho/Programmers/Week8/Programmers2_소수찾기.java
Labels: Back Tracking

#91 조수연 : Programmers 42888 오픈채팅방
  SooyeonJo/Programmers/Week9/42888_오픈채팅방.java
Labels: Hash

#92 임준규 : Programmers 42888 오픈채팅방
  Junkyu_Lim/Week9/42888.java
Labels: Hash

#93 황종훈 : Programmers 42888 오픈 채팅방
  HwangJongHoon/Programmers/Week9/오픈채팅방.java
Labels: Hash

#94 황종훈 : Programmers 42890 후보키
  HwangJongHoon/Programmers/Week9/후보키.java
Labels: Implementation

#96 임인호 : Programmers 오픈채팅방
  Inho/Programmers/Week9/Programmers2_오픈채팅방.java
Labels: Hash

#97 임인호 : Programmers 후보키
  Inho/Programmers/Week9/Programmers2_후보키.java
Labels: Back Tracking

#103 임준규 : Programmers 77485 행렬 테두리 회전하기
  Junkyu_Lim/Week10/77485.java
Labels: Queue
